name: Embed code in README

on:
  push:
    branches:
      - testing_markdown

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: testing_markdown

      - name: Embed markdown
        uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "synchronizing 2 Readme"
          no_change: "No change on Readme."
          silent: false
